import type { Product } from '../../types'

export const PRODUCTS: Product[] = [
  {
    id:          'rn',
    size:        'RN',
    label:       'Recién Nacido',
    weightRange: 'Hasta 4 kg',
    description: 'Diseñado especialmente para la piel más sensible. Protección suave y segura desde el primer día de vida.',
    features:    ['Ultra suave', 'Ombligo cuidado', 'Sin fragancia', 'Máxima absorción'],
    color:       '#E8445A',
    units:       30,
  },
  {
    id:          'p',
    size:        'P',
    label:       'Pequeño',
    weightRange: '4 a 6 kg',
    description: 'Perfecto para los primeros meses. Ajuste seguro que acompaña cada movimiento con total libertad.',
    features:    ['Ajuste ergonómico', 'Indicador de humedad', 'Elásticos suaves', 'Doble barrera'],
    color:       '#FFD700',
    units:       40,
  },
  {
    id:          'm',
    size:        'M',
    label:       'Mediano',
    weightRange: '6 a 9 kg',
    description: 'Acompaña la etapa de mayor exploración. Mayor cobertura y absorción para bebés activos.',
    features:    ['Alta absorción', 'Antiescapes', 'Suave al tacto', 'Respirabilidad'],
    color:       '#1E6FBF',
    units:       42,
  },
  {
    id:          'g',
    size:        'G',
    label:       'Grande',
    weightRange: '9 a 13 kg',
    description: 'Para bebés que ya empiezan a moverse más. Diseño activo que no limita el juego ni la diversión.',
    features:    ['Máxima movilidad', 'Absorción prolongada', 'Elásticos reforzados', 'Zona de juego'],
    color:       '#7DD9E8',
    units:       36,
  },
  {
    id:          'xg',
    size:        'XG',
    label:       'Extra Grande',
    weightRange: 'Más de 13 kg',
    description: 'Pensado para niños más activos. Ajuste amplio y cómodo con la protección que ya conocen.',
    features:    ['Cobertura amplia', 'Sin restricciones', 'Secado rápido', 'Confort duradero'],
    color:       '#1E6FBF',
    units:       30,
  },
]
